---

- name: Install Miscellaneous packages
  apt: name={{item}}
    state=latest
    update_cache=yes
    force=yes
  with_items:
    - unzip
    - curl
    - tree
    - libxml2-dev
    - libxslt-dev
    - git
    - duplicity
    - graphviz
    - ncftp
    - uuid
    - imagemagick
    - lua5.2
    - vim
    - python-boto
    - memcached
    - libyaml-dev
